name: Server pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  create_server:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Creating server / Finding public ip address
      run: |
           aws ec2 run-instances \
           --image-id ami-01e444924a2233b07 \
           --count 1 \
           --instance-type t2.micro \
           --key-name "Nikita_Relevant" \
           --region eu-central-1 \
           --security-group-ids sg-0adba3fd89dc7ef06 | awk '/"InstanceId"/ { print $2 }' | tr -d ,\"> output.txt
           echo "instance_id=$(cat output.txt)" >> GITHUB_OUTPUT
           sleep 5
           aws ec2 describe-instances \
           --instance-ids $instance_id \
           --query 'Reservations[*].Instances[*].PublicIpAddress'\
           --output text 