name: CD pipeline

on:
  push:
    branches: [ "master" ]
#on:
#  workflow_run:
#    workflows: ["CI pipeline"]
#    types:
#      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Debug
      run: |
        pwd
        ls -la
      shell: bash
    - name: Pull Docker image
      run: docker pull lorissxd/webapp_cicd:1.7
    - name: Run the containers
      run: docker compose up -d


