name: Continue Deploy

on:
  push:
    branches: [ "developer" ]


jobs:
  run_tests:
    name: Testing application
    runs-on: ubuntu-latest
    container:
      image: python:alpine
    steps:
    - uses: actions/checkout@v4
    - name: Install requirments / Run tests
      run: |
          echo "Requirements installation for test running..."
          pip install --upgrade setuptools 2>&1 >/dev/null
          pip install -r requirements.txt 2>&1 >/dev/null
          python3 -m unittest test_*.py


  build_docker:
    name: Building docker image
    needs: run_tests
    runs-on: ubuntu-latest
    outputs:
      sync_tag: ${{ steps.c.outputs.GIT_SHA_SERVER }}
    steps:
    - uses: actions/checkout@v4
    - name: Create tag for docker
      run: echo "GIT_SHA_DOCKER=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Building docker image
      run: |
          echo "Building docker image..."
          docker build -t lorissxd/webapp_cicd:$GIT_SHA_DOCKER . >/dev/null
    - name: Login to Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Push image to Dockerhub
      run: docker push lorissxd/webapp_cicd:$GIT_SHA_DOCKER >/dev/null
    - name: Taking tag from last steps
      id: c
      run: echo "GIT_SHA_SERVER=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_OUTPUT


  deploy:
    name: Deploying image to the server
    needs: build_docker
    runs-on: ubuntu-latest
    env:
      TAKE_TAG: ${{ needs.build_docker.outputs.sync_tag }}
    steps:
    - uses: actions/checkout@v4
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT}}
        envs: TAKE_TAG
        script: |
          eval $(ssh-agent -s) 1>/dev/null
          ssh-add ~/.ssh/secret_key 2>/dev/null
          cd ~/webapp_cicd
          git pull origin master
          docker rmi -f $(docker images -aq) 2>/dev/null
          sed "s~\(image: lorissxd/webapp_cicd.*\)~image: lorissxd/webapp_cicd:$TAKE_TAG~g" -i ~/webapp_cicd/docker-compose.yaml
          docker compose -f ~/webapp_cicd/docker-compose.yaml down && docker compose -f ~/webapp_cicd/docker-compose.yaml up -d

