name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:
  docker:
    timeout-minutes: 1
    runs-on: ubuntu-latest
  build:
    runs-on: self-hosted
    steps:
    - name: Pull Docker image
      run: sudo docker pull lorissxd/webapp_cicd:1.7
    - name: Run the containers
      run: docker-compose -f "docker-compose.yaml" up -d --build
