name: CI pipeline

on:
  push:
    branches: [ "master" ]


jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: python:alpine
    steps:
    - uses: actions/checkout@v4
    - name: Debug 1
      run: ls -la
    - name: Debug 2
      run: cat /etc/os-release
  build:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Debug 1
      run: ls -la
    - name: Debug 2
      run: exit 1
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Debug 1
      run: ls -la
  deploy:
    needs: push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Debug 1
      run: ls -la  
#    - name: Login for Dockerhub
#      env:
#       DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
#       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#    - name: Build the docker image
#      run: docker build -t lorissxd/webapp_cicd:1.7 .
#    - name: Push to Dockerhub
#      run: docker push lorissxd/webapp_cicd:1.7
