name: CI pipeline

on:
  push:
    branches: [ "developer" ]


jobs:
  # run_tests:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: python:alpine
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Install requirments
  #     run: pip install -r requirements.txt
  #   - name: Run tests
  #     run: python3 -m unittest test_*.py
  build:
    # needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create tag
      run: echo "GIT_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Create docker image
      run: docker build -t lorissxd/webapp_cicd:$GIT_SHA_SHORT .
    - name: Login to Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Push image to Dockerhub
      run: docker push lorissxd/webapp_cicd:$GIT_SHA_SHORT
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate the ssh key-pair
      run: 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Debug 1
      run: ls -la

#    - name: Login for Dockerhub
#      env:
#       DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
#       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#    - name: Build the docker image
#      run: docker build -t lorissxd/webapp_cicd:1.7 .
#    - name: Push to Dockerhub
#      run: docker push lorissxd/webapp_cicd:1.7
