- name: multiple command

on:
  push:
    branches: [ "master" ]


uses: appleboy/ssh-action@v1.0.3
with:
  host: ${{ secrets.SSH_HOST }}
  username: ${{ secrets.SSH_USERNAME }}
  key: ${{ secrets.SSH_KEY }}
  port: ${{ secrets.SSH_PORT }}
  script: |
    whoami
    ls -al