name: multiple command

on:
  push:
    branches: [ "master" ]

jobs:
  ssh:
    uses: actions/checkout@v4
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      key: ${{ secrets.SSH_KEY }}
      port: ${{ secrets.SSH_PORT }}
      run: |
        whoami
        ls -al