name: remote ssh command
on:
  push:
    branches: [ "master" ]

jobs:
  configure_server:
    name: Configuring server
    needs: create_server
    runs-on: ubuntu_latest
    steps:
    - uses: actions/checkout@v4
    - name: Taking ip from previous job
      run: echo $SERVER_IP
    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: $SERVER_IP
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT}}
        envs: TAKE_TAG
        script: |
          whoami
          ls
          ip addr