name: remote ssh command
on:
  push:
    branches: [ "master" ]

jobs:
  configure_server:
    name: Configuring server
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        timeout: 30s
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT}}
        script: |
          ls
          whoami