name: remote ssh command
on:
  push:
    branches: [ "master" ]

jobs:
  test_job:
    name: Just test variable
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.create_tag.outputs.NEW_TAG }}
    steps:
    - name: Create tag
      id: create_tag
      run: echo "NEW_TAG"=1.8 >> $GITHUB_OUTPUT

  build:
    needs: test_job
    name: Build
    runs-on: ubuntu-latest
    env:
      NEW_TAG: ${{ needs.test_job.outputs.new_tag }}
    steps:
    - name: Echo variable
      run: echo NEW_TAG=$NEW_TAG
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT}}
        envs: NEW_TAG
        script: |
          sed "s~\(image: lorissxd/webapp_cicd.*\)~image: lorissxd/webapp_cicd:$NEW_TAG~g" -i ~/webapp_cicd/docker-compose.yaml
          docker compose -f ~/webapp_cicd/docker-compose.yaml down && docker compose -f ~/webapp_cicd/docker-compose.yaml up -d